- name: Install HTTP Packages
  when: ansible_facts['pkg_mgr'] == "dnf"
  dnf:
    name: "{{ apache_package_name }}"
    update_cache: yes
    state: present

- name: Start httpd service
  when: ansible_facts['service_mgr'] == "systemd"
  systemd: 
    name: "{{ apache_service_name }}"
    state: started
    enabled: yes

- name: Create Apache Document Root
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    owner: "apache"
    group: "apache"
    mode: "0755"

- name: Set up Apache VirtualHost
  template:
    src: "files/httpd.conf.j2"
    dest: "/etc/httpd/conf.d/{{ http_conf }}"
  notify: Restart Apache  