# WordPress Configuration
- name: Download and unpack WordPress(latest=6.1.1) 
  unarchive:
    src: "{{ wordpress_src }}"
    dest: "/var/www/{{ http_host }}"
    remote_src: yes
    creates: "/var/www/{{ http_host }}/wordpress"

- name: Set ownership
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    recurse: yes
    owner: apache
    group: apache
  notify: 
    - Restart Apache  

- name: Set permissions for directories
  shell: "/usr/bin/find /var/www/{{ http_host }}/wordpress/ -type d -exec chmod 750 {} \\;"

- name: Set permissions for files
  shell: "/usr/bin/find /var/www/{{ http_host }}/wordpress/ -type f -exec chmod 640 {} \\;"

- name: Set up wp-config
  template:
    src: "files/wp-config.php.j2"
    dest: "/var/www/{{ http_host }}/wordpress/wp-config.php"
   

