- name: Install MariaDB Packages
  when: ansible_facts['package_mgr'] == "apt"
  apt:
    update_cache: yes
    name: {{ item }}
    state: present
    loop: "{{ mariadb_modules }}"

- name: Start and Enable MariaDB
  when: ansible_facts['service_mgr'] == "systemd"
  systemd:
    name: mariadb
    state : started
    enabled: yes  

- name: Set MariaDB root password
  no_log: true
  mysql_user: 
    login_host: 
    login_user: "root"
    login_password: ""
    name: "root"
    password: "{{ mysql_root_password }}"
    state: present

- name: Create DB for WordPress
  mysql_db:
    name: "{{ mysql_wp_db }}"
    state: present
    login_user: "root"
    login_password: "{{ mysql_root_password }}"

- name: Create a DB user for WordPress
  mysql_user:
    name: "{{ mysql_wp_user }}"
    password: "{{ mysql_wp_password }}"
    priv: "{{ mysql_wp_db }}.*:ALL"
    state: present
    host:
    login_user: "root"
    login_password: "{{ mysql_root_password }}"